import type { UiLanguage } from './uiLanguage';

// Translate only product-owned fixture metadata, never the model's actual output.
const chinese: Record<string, string> = {
  'Evidence-based report': '有据可查的报告',
  'Document analysis': '文档摘录分析',
  'Plugin change contract': '插件修改要求',
  'Nexus branch and Loop contract': 'Nexus 分支与 Loop 规则',
  'Changed requirements': '多轮要求变更',
  'Supplied-source reasoning only; no live search.': '仅分析给定资料，不执行真实搜索。',
  'Provided document excerpts only; not PDF/OCR execution.': '仅分析文档摘录，不实际执行 PDF 解析或 OCR。',
  'Simulated specification only; no plugin code or deployment is executed.': '仅模拟插件功能要求，不修改代码或发布插件。',
  'Text simulation only; does not verify the real Nexus engine or recovery.': '仅进行文本模拟，不验证真实 Nexus 引擎或恢复过程。',
  'Synthetic conversation reasoning only; no current conversation is replayed.': '仅分析合成对话，不重放当前会话。',
  'Return exactly the requested JSON fields; no extra assertions or self-awarded scores.': '准确返回要求的 JSON 字段，不附加额外声明或自评分。',
  'Atlas success rate is 72 / 80 = 90%.': 'Atlas 的成功率为 72 / 80 = 90%。',
  'Boreal success rate is 45 / 50 = 90%.': 'Boreal 的成功率为 45 / 50 = 90%。',
  'Equal observed rates do not show a strictly better accuracy.': '观察成功率相同，不能声称一方准确率更高。',
  'No supplied latency evidence supports an advantage.': '给定资料没有支持耗时优势的证据。',
  'Both supplied source IDs, and no invented sources, are required.': '必须引用两个给定来源，不得虚构来源。',
  'Use the latest change: 1200 + 2800 + 700 = 4700.': '按最新变更计算：1200 + 2800 + 700 = 4700。',
  'The removed item is review.': '被移除的项目为 review。',
  'The added item is accessibility testing.': '新增项目为 accessibility testing。',
  'No attachment was read in this text-only case.': '本项纯文本样例未读取真实附件。',
  'Use both supplied excerpts and no invented attachment.': '引用两个给定摘录，不虚构附件。',
  'All original controls must remain.': '保留全部已有控制功能。',
  '25 minutes is 1500 seconds.': '25 分钟等于 1500 秒。',
  'The request does not authorize publication.': '请求未授权发布。',
  'No external tool was called.': '未调用任何外部工具。',
  'Reference the existing and requested contracts.': '同时引用已有功能和新增要求。',
  'The first increment reaches 3.': '第一次增加后达到 3。',
  'Stop after one iteration, not at the cap.': '达到条件后第一轮即停止，不跑满轮数上限。',
  'The branch is selected from the final value.': '按最终值选择分支。',
  'Pending external approval does not authorize a send.': '等待外部审批不代表已经获准发送。',
  'Reference flow rules and approval boundary.': '引用流程规则和审批边界。',
  'Only Markdown remains requested.': '最新要求仅保留 Markdown。',
  'The later user instruction cancels email.': '后续用户要求已取消邮件发送。',
  'The comparison table is explicitly retained.': '明确保留对比表格。',
  'U2 supersedes the conflicting portions of U1.': 'U2 替代 U1 中相冲突的要求。',
  'The decision is grounded in both turns.': '决定依据两轮对话。',
  'Five fixed synthetic text contracts, one baseline/candidate pair each; not a statistically significant or general business-quality benchmark.': '五类固定合成文本样例，每类一组配对；不构成统计显著或通用业务质量基准。',
  'Inputs are independent of the source task and suggested validation cases. The suite is public and reused; repeated exposure can contaminate results and is not a fresh blind holdout.': '输入独立于原任务和建议测试。样例公开且重复使用，反复接触可能影响结果，不是全新盲测。',
  'Facts and citations are checked only against the supplied fixture truths. No live search, document reader, plugin, Nexus engine, workspace or external tool is executed.': '仅按给定样例真值检查事实与引用，不运行真实搜索、文件读取、插件、Nexus、工作区或外部工具。',
  'Provider calls may incur charges. Tokens and wall time are measured; monetary cost and human interventions are not observable and remain null.': '模型调用可能计费。记录 Token 和耗时；金额与人工干预不可测，保留未知。',
  'The same resolved model and settings are used for both arms. One pass is not a reliable latency comparison; no policy, permission, task, graph or published version is changed.': '两组使用同一模型和设置。单次结果不是可靠的速度结论；不更改策略、权限、任务、Graph 或已发布版本。',
  'Comparison cancelled. Partial results are retained. Already submitted provider requests may still be billed.': '对照已停止，部分结果已保留。已提交的模型请求仍可能计费。',
  'Comparison interrupted, timed out, or its source/candidate changed. Partial results are retained; no policy was applied.': '对照中断、超时或来源/建议发生变化。保留部分结果，未应用任何策略。',
  'This comparison expired or was interrupted. Partial results are retained; start a new comparison explicitly.': '对照已过期或中断，保留部分结果；如需重试，请主动开始新对照。',
  'Evaluation was cancelled or its overall time limit expired.': '对照已取消或超过整体时限。',
  'This model call exceeded the evaluation time limit.': '本次模型调用超过评测时限。',
  'The provider returned an unusable response or could not complete this comparison. No tool was executed.': '模型返回不可用结果或未能完成本次对照。未执行任何工具。',
};

export const improvementEvaluationText = (value: string, language: UiLanguage) => language === 'zh-CN' ? chinese[value] ?? value : value;
