import type { RunEvent } from '../types';
import { translateUiText, type UiLanguage } from './uiLanguage';

const runtimeEnglish: Record<string, string> = {
  '任务已持久化': 'Task saved durably',
  '任务已进入执行队列': 'Task queued for execution',
  '调度器已接管任务': 'Scheduler took ownership of the task',
  '路由 Agent 正在理解本轮目标': 'Routing Agent is interpreting the current goal',
  '路由 Agent 已选出候选能力': 'Routing Agent selected candidate capabilities',
  '调度 Agent 正在编排本轮路径': 'Scheduling Agent is planning the current execution path',
  '调度 Agent 已确定本轮执行路径': 'Scheduling Agent selected the current execution path',
  'Harness 控制面已连接': 'Harness control plane connected',
  'Harness 控制面已断开': 'Harness control plane disconnected',
  '外部 Thread 已启动': 'External Thread started',
  '外部 Thread 已恢复': 'External Thread resumed',
  '外部 Thread 已创建分支': 'External Thread forked',
  '外部 Thread 已关闭': 'External Thread closed',
  'Harness Turn 已开始': 'Harness Turn started',
  'Harness Turn 已完成': 'Harness Turn completed',
  'Harness Turn 已中断': 'Harness Turn interrupted',
  'Harness Turn 执行失败': 'Harness Turn failed',
  'Harness Item 已开始': 'Harness Item started',
  'Harness Item 已完成': 'Harness Item completed',
  '规划器正在拆解任务': 'Planner is breaking down the task',
  '工作流计划已生成': 'Workflow plan generated',
  '规划器计划正在等待人工批准': 'Planner plan awaits human approval',
  '执行计划已批准': 'Execution plan approved',
  '执行计划已驳回': 'Execution plan rejected',
  '规划器已开始生成新版本计划': 'Planner is generating a revised plan',
  'Agent Graph 已更新': 'Agent Graph updated',
  '执行循环已启动': 'Execution loop started',
  '执行循环已完成': 'Execution loop completed',
  'Agent 工具循环': 'Agent tool loop',
  '并行 Agent 结论出现冲突，等待验证': 'Parallel Agent conclusions conflict and await verification',
  '会话 Agent Graph 已加入新能力': 'New capabilities added to the conversation Agent Graph',
  '智能体队列已更新': 'Agent queue updated',
  'Harness 操作等待人工批准': 'Harness operation awaits human approval',
  'Harness 审批已完成': 'Harness approval completed',
  '工具结果待核对': 'Tool outcome awaits verification',
  '工具结果已核对': 'Tool outcome verified',
  '节点已请求重试': 'Node retry requested',
  '节点已由操作员跳过': 'Node skipped by the operator',
  '节点已由操作员标记完成': 'Node marked complete by the operator',
  '已从选定节点重新运行': 'Execution restarted from the selected node',
  'Agent 已暂停': 'Agent paused',
  'Agent 已恢复': 'Agent resumed',
  'Agent 或模型已替换': 'Agent or model replaced',
  'Agent 结果已锁定': 'Agent result locked',
  'Agent 结果已解锁': 'Agent result unlocked',
  '审查员开始验证证据树': 'Reviewer started verifying the evidence tree',
  '审查员已完成质量门禁': 'Reviewer completed the quality gate',
  '审查员未通过，等待人工质量决策': 'Review did not pass; awaiting a human quality decision',
  '操作员已批准当前审查员结果': 'Operator approved the current review result',
  '操作员已驳回结果，等待重新规划': 'Operator rejected the result; awaiting replanning',
  '运行检查点已持久化': 'Runtime checkpoint saved durably',
  '已从检查点创建新方案': 'New branch created from the checkpoint',
  '检查点方案已合并': 'Checkpoint branches merged',
  '开始召回智能体记忆': 'Agent memory recall started',
  '智能体记忆召回完成': 'Agent memory recall completed',
  '正在沉淀本轮长期记忆': 'Saving long-term memory from the current run',
  '本轮长期记忆已可靠保存': 'Long-term memory from the current run saved durably',
  '本轮记忆无需重复保存': 'Memory from the current run does not need to be saved again',
  '长期记忆暂未保存，任务结果不受影响': 'Long-term memory was not saved; the task result is unaffected',
  '本轮记忆策略已更新': 'Memory policy for the current run updated',
  '任务执行预算已达到上限': 'Task execution budget limit reached',
  '预算接近上限，已压缩并行步骤': 'Budget is near its limit; parallel steps reduced',
  '已根据实际执行进度更新剩余时间': 'Remaining time updated from actual execution progress',
  '操作员指令已加入下一轮上下文': 'Operator instructions added to the next iteration context',
  '补充要求已接收，等待下一个安全执行点': 'Additional instructions received; awaiting the next safe execution point',
  '补充要求已应用到当前任务': 'Additional instructions applied to the current task',
  '结果 Artifact 已生成': 'Result Artifact generated',
  '复杂任务工作流已完成': 'Complex task workflow completed',
  '任务在重试后仍然失败': 'Task failed after retries',
  '任务已取消': 'Task cancelled',
  'Loop 已暂停，检查点已保存': 'Loop paused; checkpoint saved',
  'Loop 已恢复，继续处理未完成步骤': 'Loop resumed; continuing unfinished steps',
  '直接回答已完成': 'Direct answer completed',
  '直接响应已开始': 'Direct response started',
  '正在恢复持久化任务事件流': 'Reconnecting to the persisted task event stream',
  '任务仍在服务端执行，事件流恢复失败': 'Task is still running on the server; event stream reconnection failed',
  '任务已停止': 'Task stopped',
  'Loop 已暂停，检查点可继续': 'Loop paused; its checkpoint can be resumed',
  '从检查点恢复 Loop': 'Resuming Loop from its checkpoint',
  '操作员反馈已加入下一轮 Agent 上下文': 'Operator feedback added to the next Agent iteration context',
  '补充要求已送达当前执行器': 'Additional instructions delivered to the active executor',
  '当前审查员结果已由操作员批准，继续交付': 'Operator approved the current review result; continuing delivery',
  '审查结果已退回，Agent 开始重新规划并整改': 'Review result returned; Agent is replanning and correcting it',
  '已提交重规划指令': 'Replanning instructions submitted',
  '语义路由正在识别任务类型': 'Semantic router is identifying the task type',
  '自定义模型请求失败': 'Custom model request failed',
  '网关连接失败': 'Gateway connection failed',
  '绘图任务进入媒体网关': 'Image task entered the media gateway',
  '绘图请求失败': 'Image request failed',
};

// Captures are runtime names, tool names, and source prose. Never recursively translate them.
const runtimePatterns: Array<[RegExp, (...values: string[]) => string]> = [
  [/^(.+)连接提前结束，正在重新连接（第 (.*) 次）$/u, (name, attempt) => `${name}'s connection ended early; reconnecting (attempt ${attempt})`],
  [/^(.+)遇到服务限流，正在稍后重试（第 (.*) 次）$/u, (name, attempt) => `${name} was rate limited; retrying shortly (attempt ${attempt})`],
  [/^(.+)等待响应超时，正在重试（第 (.*) 次）$/u, (name, attempt) => `${name} timed out waiting for a response; retrying (attempt ${attempt})`],
  [/^(.+)遇到可恢复错误，正在重试（第 (.*) 次）$/u, (name, attempt) => `${name} encountered a recoverable error; retrying (attempt ${attempt})`],
  [/^审查员通过质量门禁(.*)$/u, (score) => `Reviewer passed the quality gate${score}`],
  [/^审查员驳回并请求修正(.*)$/u, (score) => `Reviewer rejected the result and requested corrections${score}`],
  [/^Loop 第 (.*) 轮$/u, (iteration) => `Loop iteration ${iteration}`],
  [/^已创建(.+)$/u, (name) => `Created ${name}`],
  [/^已分配步骤给(.+)$/u, (name) => `Step assigned to ${name}`],
  [/^(.+)正在组织阶段结果$/u, (name) => `${name} is composing the stage result`],
  [/^(.+)已完成阶段输出$/u, (name) => `${name} completed the stage output`],
  [/^(.+)的阶段调用未完成$/u, (name) => `${name}'s stage call did not complete`],
  [/^(.+)正在决定下一步行动$/u, (name) => `${name} is deciding the next action`],
  [/^(.+)正在读取工具结果$/u, (name) => `${name} is reading tool results`],
  [/^(.+)发送了协作消息$/u, (name) => `${name} sent a collaboration message`],
  [/^(.+)本轮无需执行$/u, (name) => `${name} does not need to run this iteration`],
  [/^(.+)正在重试$/u, (name) => `${name} is retrying`],
  [/^(.+)已中断$/u, (name) => `${name} interrupted`],
  [/^(.+)已恢复$/u, (name) => `${name} resumed`],
  [/^(.+) 已获人工批准$/u, (name) => `${name} received human approval`],
  [/^(.+) 等待人工批准$/u, (name) => `${name} awaits human approval`],
  [/^(.+) 已拒绝$/u, (name) => `${name} rejected`],
  [/^计划 v(.+) 已批准，继续执行$/u, (version) => `Plan v${version} approved; continuing execution`],
  [/^计划 v(.+) 已驳回$/u, (version) => `Plan v${version} rejected`],
  [/^工具 (.+) 已获批准，继续执行$/u, (name) => `Tool ${name} approved; continuing execution`],
  [/^工具 (.+) 已驳回$/u, (name) => `Tool ${name} rejected`],
  [/^节点 (.+) 已提交 (.+)$/u, (node, action) => `Node ${node}: submitted ${action}`],
  [/^已分配(.+?)：([\s\S]*)$/u, (name, reason) => `Assigned ${name}: ${reason}`],
  [/^报告生成 Agent 正在生成 (.+) 文件$/u, (format) => `Report Agent is generating a ${format} file`],
  [/^报告生成 Agent 已交付 (.+)$/u, (name) => `Report Agent delivered ${name}`],
  [/^已自动整理最早的 (\d+) 条消息，保留最新上下文执行。$/u, (count) => `Summarized the earliest ${count} messages; executing with the latest context.`],
  [/^已返回 (\d+) 张图片$/u, (count) => `Returned ${count} images`],
  [/^(.+?) ?开始执行$/u, (name) => `${name} started execution`],
  [/^(.+) 执行完成$/u, (name) => `${name} completed execution`],
  [/^(.+?) ?执行失败$/u, (name) => `${name} failed execution`],
  [/^(.+)已完成$/u, (name) => `${name} completed`],
];

export function translateRunEventLabel(event: Pick<RunEvent, 'label' | 'labelSource'>, language: UiLanguage): string {
  const { label } = event;
  if (event.labelSource !== 'system' || language !== 'en') return label;
  const exact = runtimeEnglish[label];
  if (exact) return exact;
  // Classification fields are platform-owned enum labels, not source text.
  const classification = label.match(/^任务分类：(.+) · (.+) · (.+)$/u);
  if (classification) return `Task classification: ${classification.slice(1).map((value) => translateUiText(value, language)).join(' · ')}`;
  for (const [pattern, format] of runtimePatterns) {
    const match = label.match(pattern);
    if (match) return format(...match.slice(1));
  }
  return translateUiText(label, language);
}
