import { createContext, useCallback, useContext, useLayoutEffect, useMemo, useState, type ReactNode } from 'react';

export type UiLanguage = 'en' | 'zh-CN';

export const DEFAULT_UI_LANGUAGE: UiLanguage = 'en';
export const UI_LANGUAGE_STORAGE_KEY = 'axiom-ui-language-v1';

type UiLanguageContextValue = {
  language: UiLanguage;
  setLanguage: (language: UiLanguage) => void;
  t: (source: string) => string;
};

const UiLanguageContext = createContext<UiLanguageContextValue | null>(null);

const improvementEnglishByChinese: Record<string, string> = {
  '复盘、对照，再决定是否试用。现有任务保持不变。': 'Review, compare, then decide what to try. Existing tasks stay unchanged.',
  '样例中有改善': 'Improved on these cases',
  '无明显变化': 'No clear change',
  '样例中出现退化': 'Regression on these cases',
  '证据不足': 'Inconclusive',
  '正在对照': 'Comparing',
  '对照完成': 'Comparison complete',
  '对照未完成': 'Comparison incomplete',
  '已停止对照': 'Comparison stopped',
  '原任务或建议已更改，请刷新改进记录。': 'The source or suggestion changed. Refresh improvements.',
  '对照记录读取失败，请重试。': 'Could not load comparisons. Try again.',
  '建议或对照状态已更改，请刷新后重试。': 'The suggestion or comparison changed. Refresh before trying again.',
  '操作未完成，请刷新查看对照状态。': 'The operation did not complete. Refresh to check the comparison.',
  '独立样例对照': 'Independent case comparison',
  '先对照，再决定': 'Compare before deciding',
  '刷新对照记录': 'Refresh comparisons',
  '用同一模型比较原始做法与加入建议后的结果。仅验证固定样例，不改动真实任务。': 'Compare baseline and suggested guidance with the same model. Fixed cases only; real tasks stay unchanged.',
  '评测范围与用量': 'Scope and usage',
  '个样例': 'cases',
  '文本契约与模拟场景，不执行真实搜索、文件写入、插件或 Nexus。': 'Text contracts and simulated scenarios only. No live search, file writes, plugin execution, or Nexus runs.',
  '最多模型调用': 'Maximum model calls',
  '每次输出上限': 'Output limit per call',
  '固定样例可被重复使用，不是永久盲测，也不代表所有真实任务的提升。': 'Fixed cases can be reused: this is not a permanently blind test or proof of gains on all real tasks.',
  '使用原任务模型进行对照，会产生模型用量。': 'Use the source task’s model for comparison. Model usage may incur charges.',
  '开始对照': 'Start comparison',
  '停止对照': 'Stop comparison',
  '可以离开页面，记录会保留。停止不会退回已经产生的模型用量。': 'You can leave; records are saved. Stopping does not refund model usage already incurred.',
  '对照记录': 'Comparison history',
  '选择对照记录': 'Select comparison',
  '结论仅适用于本次样例；未自动采用建议。': 'This result applies only to these cases. The suggestion has not been applied.',
  '本次对照结果': 'Comparison results',
  '指标': 'Metric',
  '原始做法': 'Baseline',
  '未加入建议': 'Without guidance',
  '对同一固定样例分别加入或不加入建议；不是原任务重跑。': 'The same fixed case, with and without guidance—not a replay of the original task.',
  '加入建议': 'With guidance',
  '通过检查': 'Checks passed',
  '模型调用耗时': 'Model call duration',
  '金额与人工干预': 'Cost and human intervention',
  '未测量，不以零代替': 'Not measured, not zero',
  '改善检查': 'Improved checks',
  '退化检查': 'Regressed checks',
  '查看逐项证据': 'Inspect case evidence',
  '查看模型原文': 'View model output',
  '无输出': 'No output',
  '验证边界': 'Validation limits',
  '评测版本': 'Suite version',
  '建议版本': 'Suggestion revision',
  '任务改进': 'Task improvements',
  '仅生成建议，不修改现有任务。效果尚未验证。': 'Suggestions only. Existing tasks stay unchanged. Benefits are not yet verified.',
  '正在复盘': 'Reviewing',
  '待查看': 'Ready to review',
  '已保存': 'Saved',
  '已忽略': 'Dismissed',
  '未完成': 'Incomplete',
  '任务描述': 'Task instructions',
  '智能体分工': 'Agent selection',
  '执行步骤': 'Execution steps',
  '结果核验': 'Result verification',
  '改进记录读取失败，请刷新重试。': 'Could not load improvements. Refresh to try again.',
  '建议已在其他页面更改，请刷新后重试。': 'This suggestion changed elsewhere. Refresh before trying again.',
  '原任务或建议已不可访问，请刷新列表。': 'The task or suggestion is no longer accessible. Refresh the list.',
  '操作未完成，请先刷新查看记录后重试。': 'The operation did not complete. Refresh to check its status before retrying.',
  '未记录': 'Not recorded',
  '刷新改进记录': 'Refresh improvements',
  '关闭提示': 'Dismiss notice',
  '从一次任务开始': 'Start with a task',
  '选择已结束的任务': 'Choose a finished task',
  '最近已结束任务': 'Recently finished tasks',
  '正在读取任务…': 'Loading tasks…',
  '暂无可复盘的任务': 'No finished tasks yet',
  '想改善什么': 'What would you improve',
  '可选': 'Optional',
  '例如：减少重复搜索，让结论更完整': 'For example: fewer repeated searches, more complete conclusions',
  '延续一份建议': 'Build on a suggestion',
  '独立复盘': 'Start fresh',
  '正在处理…': 'Working…',
  '生成改进建议': 'Generate suggestions',
  'Agent 正在复盘。可以离开页面，稍后回来查看。': 'An Agent is reviewing the task. You can leave and check back later.',
  '先完成一次任务，再来查看如何改进。': 'Finish a task first, then come back to explore improvements.',
  '改进历史': 'Improvement history',
  '正在读取…': 'Loading…',
  '建议会保存在这里。': 'Your suggestions will appear here.',
  '改进建议详情': 'Improvement details',
  '让下一次任务更有把握': 'Make the next task better informed',
  '选一项已结束的任务，Agent 会结合执行记录提出可验证的建议。': 'Choose a finished task. An Agent will use its execution records to suggest testable changes.',
  '尚未验证': 'Not validated',
  '原任务 Agent': 'Original Agents',
  '原任务 Token': 'Original tokens',
  '原任务耗时': 'Original duration',
  '本次复盘 Token': 'Review tokens',
  '复盘模型': 'Review model',
  'Agent 正在复盘执行记录…': 'An Agent is reviewing the execution records…',
  '这次复盘未完成': 'The review did not complete',
  '原任务未被修改。检查模型配置后，可重新生成建议。': 'The original task is unchanged. Check your model settings, then try again.',
  '查看原因': 'View details',
  '重新选择此任务': 'Select this task again',
  '执行记录中的线索': 'Observations from the records',
  'Agent 提出的建议': 'Agent suggestions',
  '建议测试': 'Suggested tests',
  '未执行': 'Not run',
  '预期行为': 'Expected behavior',
  '需要留意': 'Things to watch',
  '保存建议': 'Save suggestion',
  '忽略建议': 'Dismiss suggestion',
  '带建议新建对话': 'Try in a new conversation',
  '复制建议': 'Copy suggestion',
  '已复制': 'Copied',
  '新对话草稿': 'New conversation draft',
  '先检查，再发送': 'Review before sending',
  '只填入新对话草稿，不自动发送，不携带附件或原 Nexus 流程。': 'This opens an unsent draft. Attachments and the original Nexus workflow are not included.',
  '新对话草稿内容': 'New conversation draft content',
  '试用提醒': 'Trial notes',
  '打开新对话': 'Open new conversation',
  '你还有未发送文字或附件。继续会替换文字并清除附件，请先返回对话保留原输入和附件。': 'You have unsent text or attachments. Continuing will replace the text and clear attachments. Return to Chat and keep your original input and attachments first.',
  '我已保留原输入和附件': 'I have kept my original input and attachments',
  '替换输入并打开新对话': 'Replace input and open a new conversation',
};

const englishByChinese: Record<string, string> = {
  ...improvementEnglishByChinese,
  '任务台': 'Control Room',
  '任务管理': 'Tasks',
  '对话': 'Chat',
  '项目空间': 'Projects',
  '模板库': 'Templates',
  '日程': 'Schedules',
  '智能体工作室': 'Agent Studio',
  '运行观测': 'Operations',
  '插件': 'Plugins',
  '新建任务': 'New task',
  '新建对话': 'New conversation',
  '当前模型': 'Active model',
  '生产就绪': 'Production readiness',
  '运行设置': 'Runtime settings',
  '系统状态': 'System status',
  '系统运行状态': 'System status',
  '关闭系统运行状态': 'Close system status',
  '界面主题': 'Interface theme',
  '选择界面主题': 'Choose interface theme',
  '主题': 'Theme',
  '曜石绿': 'Obsidian green',
  '黑金': 'Black gold',
  '深灰绿': 'Deep graphite',
  '石墨银蓝': 'Graphite blue',
  '近黑 · 薄荷绿 · 柔金': 'Near black · mint · soft gold',
  '墨黑 · 香槟金 · 暖白': 'Ink black · champagne · warm white',
  '深灰 · 冷银 · 薄荷绿': 'Deep gray · cool silver · mint',
  '深石墨 · 银蓝 · 冷白': 'Deep graphite · silver blue · cool white',
  '开始工作': 'Get started',
  '今天想交付什么？': 'What would you like to deliver today?',
  '直接开始': 'Start directly',
  '发起第一次对话': 'Start your first conversation',
  '让路由 Agent 按目标选择能力': 'Let the Router Agent select the right capabilities',
  '做一个小工具': 'Build a small tool',
  '创建插件': 'Create a plugin',
  '从空白插件开始与 Agent 共创': 'Co-create with an Agent from a blank plugin',
  '编排协作': 'Orchestrate collaboration',
  '搭建 Agent Nexus': 'Build an Agent Nexus',
  '组合 Agent、分支与 Loop': 'Combine Agents, branches, and Loops',
  '暂不引导': 'Skip for now',
  '关闭首次使用引导': 'Close getting started',
  '以后不再显示': 'Do not show again',
  '排队中': 'Queued',
  '运行中': 'Running',
  '已完成': 'Completed',
  '失败/取消': 'Failed / cancelled',
  '审查通过率': 'Review pass rate',
  '暂无审查数据': 'No review data',
  '暂无时长数据': 'No duration data',
  '较过去 24 小时 新增': 'New in the past 24 hours',
  '与过去 24 小时持平': 'Unchanged from the past 24 hours',
  '基于真实 review.completed 事件': 'Based on actual review.completed events',
  '每日工作进程': 'Daily activity',
  '当日全部工作进程，可上下滚动': 'All activity for the day · scroll to view',
  '当日没有任务记录': 'No task activity for this day',
  '近七日 Token 趋势': '7-day Token trend',
  '近七日 Token 消耗': '7-day Token usage',
  '数据来自最近': 'Data from the last',
  '我的任务': 'My tasks',
  '当前任务依赖层级': 'Current task dependencies',
  '实时任务轨道': 'Live task orbit',
  '暂无任务': 'No tasks',
  '暂无任务，提交一个目标后将出现在这里。': 'No tasks yet. Submit a goal to begin.',
  '选择或提交一个任务查看详情': 'Select or submit a task to view details',
  '选择一个任务': 'Select a task',
  '恢复正面视角': 'Return selection to front',
  '将选中任务转到正前方': 'Bring the selected task to the front',
  '当前': 'Current',
  '最新': 'Latest',
  '计划': 'Plan',
  '执行': 'Execute',
  '审查': 'Review',
  '交付': 'Deliver',
  '意图': 'Intent',
  '意图到交付': 'Intent to delivery',
  '执行链': 'Execution chain',
  '负责人': 'Owner',
  '会话': 'Conversation',
  '阶段': 'Stage',
  '难度': 'Difficulty',
  '路由依据': 'Routing rationale',
  '暂无路由说明。': 'No routing rationale available.',
  '审查发现': 'Review findings',
  '完整性缺口': 'Completeness gaps',
  '必须整改项': 'Required corrections',
  '交付凭据': 'Delivery evidence',
  '执行结果': 'Execution result',
  '执行完成': 'Execution completed',
  '执行未完成': 'Execution incomplete',
  '执行待核对': 'Execution not confirmed',
  '人工接受': 'Human acceptance',
  '已接受': 'Accepted',
  '未记录': 'Not recorded',
  '事实核验': 'Factual verification',
  '事实待核验': 'Facts not verified',
  '来源可追溯': 'Traceable source',
  '来源未核对': 'Source not checked',
  '接续可用结果': 'Continue from an available result',
  '暂停并检查交付条件': 'Pause and review delivery criteria',
  '最近两次执行未完成，或缺少可追溯来源与人工接受记录': 'The two latest runs are incomplete or lack traceable sources and human acceptance',
  '此前存在可接续的完成结果': 'Earlier runs have reusable completed results',
  '步骤完成': 'steps completed',
  '已验证': 'Verified',
  '来源支持': 'Source-backed',
  '未验证': 'Unverified',
  '存在冲突': 'Conflicted',
  '已恢复失败': 'Recovered failures',
  '人工审核': 'Human review',
  '审核意见': 'Review note',
  '填写审核意见（可选）': 'Add a review note (optional)',
  '驳回并整改': 'Reject and revise',
  '批准交付': 'Approve delivery',
  '重新提交': 'Resubmit',
  '删除': 'Delete',
  '删除中…': 'Deleting…',
  '确认删除？': 'Confirm deletion?',
  '取消': 'Cancel',
  '处理中…': 'Processing…',
  '确认按当前结果交付？': 'Deliver the current result?',
  '确认让 Agent 重新整改？': 'Ask the Agent to revise the result?',
  '确认交付': 'Confirm delivery',
  '重新规划并整改': 'Replan and revise',
  '对话工作区': 'Conversation workspace',
  '最近对话': 'Recent conversations',
  '回到最新消息': 'Jump to latest message',
  '新对话': 'New conversation',
  '开始对话': 'Start a conversation',
  '你': 'You',
  '本轮路径': 'Route this turn',
  '直接回答': 'Direct response',
  '单 Agent': 'Single Agent',
  'Agent 小组': 'Agent team',
  '完整工作流': 'Full workflow',
  '对话 Agent': 'Conversation Agent',
  '研究员': 'Researcher',
  '分析员': 'Analyst',
  '工程师': 'Builder',
  '审查员': 'Reviewer',
  '综合 Agent': 'Synthesis Agent',
  '架构设计': 'Architecture design',
  '实现': 'Implementation',
  '质量审查': 'Quality review',
  '联网检索': 'Web research',
  '证据核验': 'Evidence verification',
  '视觉生成': 'Visual generation',
  '文档分析': 'Document analysis',
  '报告制作': 'Report authoring',
  '待命': 'Idle',
  '任务路由': 'Task routing',
  '整理上下文': 'Preparing context',
  'Agent 执行': 'Agent execution',
  '执行异常': 'Execution error',
  '路由 Agent 正在识别任务类型': 'Router Agent is identifying the task type',
  '上下文 Agent 正在整理资料': 'Context Agent is preparing the material',
  '执行 Agent 正在组织回答': 'Execution Agent is preparing the response',
  '打开视频': 'Open video',
  '复制': 'Copy',
  '需要你决定下一步': 'Your decision is required',
  '质量审查未通过，Agent 已暂停在交付前。': 'Quality review did not pass. The Agent paused before delivery.',
  '补充整改要求（可选）': 'Add revision requirements (optional)',
  '继续整改': 'Continue revising',
  '按当前结果交付': 'Deliver current result',
  '补充要求已接收，将在下一步骤应用': 'Guidance received and will apply at the next step',
  '补充要求已送达当前执行器': 'Guidance delivered to the active executor',
  '补充要求已应用到当前任务': 'Guidance applied to the current task',
  '补充要求，将在下一步骤应用': 'Add guidance for the next step',
  '当前快速回答完成后可继续提问': 'You can continue after the current response finishes',
  '输入消息，Enter 发送，Shift + Enter 换行': 'Type a message · Enter to send · Shift + Enter for a new line',
  '分析': 'Analyze',
  '构建': 'Build',
  '决策': 'Decide',
  '任务执行中暂不支持追加附件': 'Attachments cannot be added while a task is running',
  '添加图片或文件': 'Add images or files',
  '暂停': 'Pause',
  '停止': 'Stop',
  '继续': 'Resume',
  '加入当前任务': 'Add to current task',
  '发送消息': 'Send message',
  '输入目标，提交给运行时': 'Describe a goal for the runtime',
  '已接收，等待下一步骤': 'Received · waiting for the next step',
  '已送达当前执行器': 'Delivered to the active executor',
  '已应用到当前任务': 'Applied to the current task',
  '系统正在怎样工作': 'How the system is working',
  '真实任务 / 事件 / SSE': 'Real tasks / events / SSE',
  '返回任务台': 'Back to Control Room',
  '运行就绪': 'Runtime ready',
  '本地模式': 'Local mode',
  '运行受阻': 'Runtime blocked',
  '核心': 'Core',
  '推理图': 'Reasoning graph',
  '事件流': 'Event stream',
  '自主核心': 'Autonomous core',
  '协作事件': 'Collaboration events',
  '节点检查器': 'Agent inspector',
  '在核心或推理图中选择一个节点查看真实上下文。': 'Select an Agent in the core or graph to inspect its actual context.',
  '把目标交给运行时，实时观察路由、推理与协作。': 'Give the runtime a goal and watch routing, reasoning, and collaboration live.',
  'AXIOM / 自主运行时': 'AXIOM / AUTONOMOUS RUNTIME',
  '新插件': 'New plugin',
  '先确定外观和窗口，再由 Agent 完成功能': 'Choose the appearance and window first, then let an Agent build the functionality',
  '名称': 'Name',
  '说明': 'Description',
  '可见范围': 'Visibility',
  '仅自己': 'Private',
  '团队共享': 'Team shared',
  '宽度': 'Width',
  '高度': 'Height',
  '图标材质': 'Icon material',
  '随机分配': 'Randomize',
  '创建后进入 Agent 设计对话': 'Continue to an Agent design conversation after creation',
  '创建空白插件': 'Create blank plugin',
  '插件列表': 'Plugin list',
  '从一个插件开始': 'Start with a plugin',
  '让 Agent 帮你创建，或安装团队已经审核的插件。': 'Build one with an Agent or install a team-approved plugin.',
  'Agent 创建': 'Create with Agent',
  '浏览市场': 'Browse market',
  '我的插件': 'My plugins',
  '插件市场': 'Plugin market',
  '待审核': 'Pending review',
  '发布': 'Publish',
  '卸载': 'Uninstall',
  '升级': 'Upgrade',
  '打开': 'Open',
  '搜索插件市场': 'Search plugin market',
  '搜索名称或用途': 'Search by name or purpose',
  '搜索': 'Search',
  '没有匹配的插件': 'No matching plugins',
  '市场正在等待第一个插件': 'The market is waiting for its first plugin',
  '换个关键词再试一次。': 'Try another keyword.',
  '团队插件通过管理员审核后会出现在这里。': 'Team plugins appear here after administrator review.',
  '清除搜索': 'Clear search',
  '已审核': 'Reviewed',
  '团队可复用插件': 'Reusable team plugin',
  '安装': 'Install',
  '恢复安全版本': 'Restore safe version',
  '没有待审核插件': 'No plugins awaiting review',
  '新的市场版本提交后会出现在这里。': 'New market submissions will appear here.',
  '提交人': 'Submitted by',
  '驳回': 'Reject',
  '通过': 'Approve',
  '当前版本': 'Current version',
  '可以发布': 'Ready to publish',
  '需要处理': 'Action required',
  '正在检查': 'Checking',
  '重新检查': 'Check again',
  '本版本权限': 'Permissions in this version',
  '不申请额外权限': 'No additional permissions',
  '完整性': 'Integrity',
  '部署要求签名': 'Signature required by deployment',
  '历史版本': 'Version history',
  '恢复会创建一个新的草稿版本': 'Restoring creates a new draft version',
  '修改插件后，这里会保留可恢复版本。': 'Restorable versions appear here after a plugin is changed.',
  '恢复': 'Restore',
  '请选择': 'Select an option',
  '正在删除': 'Deleting',
  '确认卸载': 'Confirm uninstall',
  '确认撤回': 'Confirm withdrawal',
  '通过市场审核？': 'Approve this market submission?',
  '驳回这个版本？': 'Reject this version?',
  '审核备注': 'Review note',
  '记录本次审核依据': 'Record the basis for this review',
  '告诉发布者需要修改什么': 'Tell the publisher what must change',
  '确认通过': 'Confirm approval',
  '确认驳回': 'Confirm rejection',
  '项目': 'Projects',
  '创建项目': 'Create project',
  '创建第一个项目': 'Create your first project',
  '项目名称': 'Project name',
  '项目目标': 'Project goal',
  '验收标准': 'Acceptance criteria',
  '当前团队': 'Current team',
  '成员': 'Members',
  '审核人': 'Reviewer',
  '项目知识': 'Project knowledge',
  '决策记录': 'Decision log',
  '项目通知': 'Project notifications',
  '进行中的项目': 'Active projects',
  '还没有项目': 'No projects yet',
  'Agent Nexus · 智能体枢纽': 'Agent Nexus',
  '新的 Agent Nexus': 'New Agent Nexus',
  'Agent Nexus 名称': 'Agent Nexus name',
  '运行 Agent Nexus': 'Run Agent Nexus',
  '停止 Agent Nexus': 'Stop Agent Nexus',
  '测试与发布': 'Test and release',
  'Nexus 设置': 'Nexus settings',
  '保存并关闭': 'Save and close',
  '删除这个 Nexus': 'Delete this Nexus',
  'Agent 设置': 'Agent settings',
  'Agent 目标': 'Agent goal',
  'Agent 能力': 'Agent capabilities',
  '执行参数由 AXIOM 自动安排，失败时会自动恢复。': 'AXIOM manages execution settings and recovery after failures.',
  'Agent Nexus 待命': 'Agent Nexus is idle',
  'Agent Nexus 已排队': 'Agent Nexus is queued',
  '调度器正在规划 Agent Nexus': 'The scheduler is planning Agent Nexus',
  'Agent Nexus 正在执行': 'Agent Nexus is running',
  '质量检查正在进行': 'Quality review is in progress',
  'Agent Nexus 已暂停': 'Agent Nexus is paused',
  '执行计划等待你的确认': 'The execution plan awaits your approval',
  'Agent Nexus 等待你处理': 'Agent Nexus needs your decision',
  'Agent Nexus 执行完成': 'Agent Nexus execution completed',
  'Agent Nexus 已保存部分结果': 'Agent Nexus saved a partial result',
  'Agent Nexus 执行未完成': 'Agent Nexus execution incomplete',
  'Agent Nexus 已停止': 'Agent Nexus stopped',
  '重新连接任务': 'Reconnect to task',
  '重新读取历史': 'Reload history',
  '等计划审批': 'Awaiting plan approval',
  '等人工审核': 'Awaiting human review',
  '等人工处理': 'Awaiting human action',
  '审核中': 'Reviewing',
  '已取消': 'Cancelled',
  '内置 Agent': 'Built-in Agent',
  '私有 Agent': 'Private Agent',
  '调度器正在启动 Agent Nexus': 'The scheduler is starting Agent Nexus',
  '汇总 Agent 正在生成 Nexus 输出': 'The synthesis Agent is generating Nexus output',
  'Agent Nexus 执行失败': 'Agent Nexus execution failed',
  '查看': 'View',
  '进行中': 'In progress',
  '未完成': 'Incomplete',
  '未启用': 'Not enabled',
  '暂无任务输入。': 'No task input available.',
  '个 Artifact': 'Artifacts',
  '次工具回执': 'tool receipts',
  '任务执行': 'Task execution',
  '中等': 'Moderate',
  '研究任务': 'Research task',
  '小组协作': 'Agent team',
  '问答': 'Question answering',
  '实现任务': 'Implementation task',
  '决策任务': 'Decision task',
  '运维任务': 'Operations task',
  '创作任务': 'Creative task',
  '任务': 'Task',
  '简易': 'Trivial',
  '简单': 'Easy',
  '较难': 'Hard',
  '复杂': 'Complex',
  '未分类': 'Unclassified',
  '直接响应': 'Direct response',
  '单智能体': 'Single Agent',
  '自定义路由': 'Custom route',
  '暂无阶段': 'No stage yet',
  '未知阶段': 'Unknown stage',
  '等待执行': 'Waiting to execute',
  '任务规划': 'Task planning',
  '计划审批': 'Plan approval',
  '结果汇总': 'Result synthesis',
  '执行失败': 'Execution failed',
  '工具执行': 'Tool execution',
  '质量门禁': 'Quality gate',
  '专注执行 Agent': 'Focused execution Agent',
  '版本与检查点': 'Versions and checkpoints',
  '刷新版本': 'Refresh versions',
  '正在读取版本…': 'Loading versions...',
  '任务执行后会自动保存可恢复版本。': 'Restorable versions are saved after task execution.',
  '继续处理': 'Follow-up actions',
  '报告': 'Report',
  '跟进': 'Follow-up',
  '明天一次': 'Once tomorrow',
  '每天': 'Daily',
  '每周': 'Weekly',
  '每月': 'Monthly',
  'Agent 干预': 'Agent controls',
  '选择 Agent': 'Select Agent',
  '已暂停，等待恢复': 'Paused, awaiting recovery',
  '局部重跑': 'Rerun step',
  '锁定结果': 'Lock result',
  '解锁': 'Unlock',
  '替换': 'Replace',
  '替换模型名称': 'Replacement model name',
  '本任务长期记忆': 'Long-term memory for this task',
  '关闭长期记忆': 'Disable long-term memory',
  '开启长期记忆': 'Enable long-term memory',
  '交付反馈': 'Delivery feedback',
  '准确性': 'Accuracy',
  '证据': 'Evidence',
  '速度': 'Speed',
  '路由': 'Routing',
  '工具': 'Tools',
  '呈现': 'Presentation',
  '哪里做得好，哪里需要改进': 'What worked well and what needs improvement?',
  '修订答案（可选）': 'Revised answer (optional)',
  '纠正证据（可选）': 'Correct evidence (optional)',
  '证据图': 'Evidence graph',
  '已通过': 'Approved',
  '用户事实': 'User fact',
  '工具结果': 'Tool result',
  '外部来源': 'External source',
  '上游交接': 'Upstream handoff',
  '模型推断': 'Model inference',
  '说明正确事实或来源': 'Describe the correct fact or source',
  '用量未提供': 'Usage unavailable',
  '耗时未提供': 'Duration unavailable',
  '平台': 'Platform',
  '私有': 'Private',
  '创建 Agent 草稿': 'Create Agent draft',
  '生成待审核的自定义 Agent，不会自动发布。': 'Create a custom Agent draft for review without publishing it automatically.',
  '搜索工作区': 'Search workspace',
  '在已挂载工作区中查找文件和内容。': 'Find files and content in the mounted workspace.',
  '阅读工作区文件': 'Read workspace file',
  '读取工作区中的文本文件。': 'Read a text file from the workspace.',
  '阅读文档': 'Read document',
  '读取 Markdown、JSON、YAML、XML 和文本文件。': 'Read Markdown, JSON, YAML, XML, and text files.',
  '读取表格': 'Read table',
  '读取 CSV 或 JSON 表格。': 'Read a CSV or JSON table.',
  '获取网页或 API': 'Fetch page or API',
  '读取允许访问的 HTTP/HTTPS 内容。': 'Read permitted HTTP/HTTPS content.',
  '打开网页': 'Open webpage',
  '打开允许访问的公开网页并读取正文。': 'Open a permitted public webpage and read its content.',
  '查询数据库': 'Query database',
  '执行只读查询，不会修改数据。': 'Run a read-only query without modifying data.',
  '查看代码状态': 'View code status',
  '查看工作区 Git 状态。': 'View the workspace Git status.',
  '查看代码差异': 'View code diff',
  '查看当前代码改动。': 'View the current code changes.',
  '查看代码分支': 'View code branches',
  '查看当前分支信息。': 'View current branch information.',
  '查看提交记录': 'View commit history',
  '查看近期本地 Git 提交。': 'View recent local Git commits.',
  '运行测试': 'Run tests',
  '运行受限的项目测试命令。': 'Run a restricted project test command.',
  '写入文件': 'Write file',
  '经人工批准后写入工作区文件。': 'Write a workspace file after human approval.',
  '修改文件': 'Patch file',
  '经人工批准后精确修改工作区文件。': 'Precisely modify a workspace file after human approval.',
  '关闭插件': 'Close plugin',
  '隔离运行': 'Isolated runtime',
  '平台 Agent 已连接': 'Platform Agent connected',
  'Agent 交接': 'Agent handoff',
  '完整': 'Complete',
  '部分完成': 'Partially completed',
  '受阻': 'Blocked',
  '次': 'times',
  '条证据': 'evidence items',
  '个未决问题': 'open questions',
  '选择分支方案': 'Select branch',
  '选择检查点': 'Select checkpoint',
  '步': 'steps',
  '交付版本': 'Delivery version',
  '执行版本': 'Execution version',
  '无失败项': 'No failed steps',
  '旧版本仅可查看': 'Older version is read-only',
  '这个版本接下来需要怎样调整（可选）': 'Changes to make from this version (optional)',
  '沿用计划': 'Keep plan',
  '重新规划': 'Replan',
  '从此继续': 'Continue from here',
  '比较': 'Compare',
  '合并方案': 'Merge branch',
  '连接设置': 'Connection settings',
  'Nexus 端点设置': 'Nexus endpoint settings',
  '移除当前选择': 'Remove selection',
  '关闭设置': 'Close settings',
  '输入': 'Input',
  '输出': 'Output',
  '运行全部测试': 'Run all tests',
  '发布当前草稿': 'Publish current draft',
  '日程 Agent': 'Schedule Agent',
  '什么时候，替你完成什么？': 'What should be done, and when?',
  '用一句话安排。保存前先确认，到点后再由 Agent 自动分工。': 'Describe it in one sentence. Confirm before saving, then Agents will coordinate at run time.',
  '下一项': 'Up next',
  '暂无待执行日程': 'No upcoming schedules',
  '正在理解': 'Understanding',
  '生成草案': 'Generate draft',
  '接续已验证结果': 'Continue from a verified result',
  '不接续，独立执行': 'Run independently',
  '待确认的日程草案': 'Schedule draft awaiting confirmation',
  '待确认': 'Awaiting confirmation',
  'Agent 自动编排': 'Automatic Agent orchestration',
  '重新描述': 'Revise description',
  '保存中': 'Saving',
  '确认并启用': 'Confirm and enable',
  '日程计划': 'Schedule plan',
  '执行计划': 'Execution plan',
  '未来安排正常': 'Upcoming schedule is healthy',
  '日历范围': 'Calendar range',
  '本周': 'This week',
  '未来 35 天': 'Next 35 days',
  '峰值负载': 'Peak load',
  '高频日程已折叠': 'High-frequency schedules collapsed',
  '按 30 分钟窗口估算': 'Estimated in 30-minute windows',
  '空闲': 'Available',
  '日程健康建议': 'Schedule health recommendations',
  '健康 Agent': 'Health Agent',
  '已确认的日程调整': 'Confirmed schedule adjustments',
  '已确认调整': 'Adjustment confirmed',
  '已删除日程': 'Deleted schedule',
  '高级设置：固定间隔': 'Advanced: fixed interval',
  '标题': 'Title',
  '任务目标': 'Task goal',
  '间隔（分钟）': 'Interval (minutes)',
  '任务方式': 'Task mode',
  '保存固定间隔': 'Save fixed interval',
  '已启用日程': 'Enabled schedules',
  '还没有日程': 'No schedules yet',
  '自动编排': 'Automatic orchestration',
  '启动中': 'Starting',
  '立即运行': 'Run now',
  '运行记录': 'Run history',
  '确认删除': 'Confirm deletion',
  '还没有运行记录': 'No run history yet',
  '等待 Agent 路由': 'Waiting for Agent routing',
  'Agent 正在编排': 'Agent is orchestrating',
  '手动触发': 'Manual trigger',
  '自动触发': 'Automatic trigger',
  '确认日程调整': 'Confirm schedule adjustment',
  '确认调整': 'Confirm adjustment',
  '正在应用': 'Applying',
  '智能体队列已更新': 'Agent queue updated',
  '用一句话描述你想要的 Agent，平台会自动接入调度。': 'Describe the Agent you need. The platform will connect it to orchestration automatically.',
  '新建 Agent': 'New Agent',
  'Agent 名称': 'Agent name',
  '它要帮你做什么': 'What should it do?',
  '高级设置': 'Advanced settings',
  '保存 Agent': 'Save Agent',
  '暂无自定义 Agent，点击“新建 Agent”开始。': 'No custom Agents yet. Select “New Agent” to begin.',
  '我的模板': 'My templates',
  '标准模板': 'Standard templates',
  '还没有模板': 'No templates yet',
  '暂无标准模板': 'No standard templates',
  '导入': 'Import',
  '导出': 'Export',
  '共享': 'Share',
  '运行视图': 'Runtime view',
  '运营观测': 'Operations',
  '活动队列': 'Active queue',
  '队列与租约': 'Queues and leases',
  '模型表现': 'Model performance',
  '工具失败分布': 'Tool failure distribution',
  '质量与人工接管': 'Quality and human intervention',
  'SLA 概览': 'SLA overview',
  '暂无数据': 'No data',
  '刷新': 'Refresh',
  '严重': 'Critical',
  '关注': 'Warning',
  '提示': 'Notice',
  '主要服务已通过检测': 'Core services passed live checks',
  '所有主要服务均已通过实时检测。': 'All core services passed live checks.',
  '主要功能可用': 'Core functions are available',
  '可以继续使用，少数增强能力尚未开启。': 'Core use is available; some optional capabilities are not enabled.',
  '部分功能暂不可用': 'Some capabilities are unavailable',
  '请检查下方项目后再运行复杂任务。': 'Review the items below before running complex tasks.',
  '模型配置': 'Model configuration',
  '文本模型': 'Text model',
  '视觉模型': 'Vision model',
  '绘图模型': 'Image model',
  '视频模型': 'Video model',
  '模型名称': 'Model name',
  '服务位置': 'Service location',
  '本地服务': 'Local service',
  '互联网 API': 'Internet API',
  '本地': 'Local',
  '互联网': 'Internet',
  '使用默认配置': 'Use default configuration',
  '应用设置': 'Apply settings',
  '安全保存凭据': 'Store credential securely',
  '更新安全凭据': 'Update secure credential',
  '已安全保存': 'Stored securely',
  '（可选）': '(optional)',
  '本地服务无需密钥时留空': 'Leave blank if the local service does not require a key',
  '输入互联网 API 密钥': 'Enter the Internet API key',
  '服务端视觉模型未就绪': 'Server-side vision model is not ready',
  '未配置服务端绘图密钥': 'Server-side image credential is not configured',
  '尚未配置，视频制作 Agent 暂不可用': 'Not configured; the Video Agent is unavailable',
  '视频服务未配置': 'Video service not configured',
  '自定义模型服务': 'Custom model service',
  '本地视频模型': 'Local video model',
  '工具与就绪': 'Tools and readiness',
  '关闭': 'Close',
  '全部': 'All',
  '个任务': 'tasks',
  '今天': 'Today',
  '工作流': 'Workflow',
  '通知': 'Notifications',
  '发送': 'Send',
  '任务范围': 'Task range',
  '前一天': 'Previous day',
  '后一天': 'Next day',
  '新任务': 'New task',
  '尚未调用 Agent': 'No Agent has been invoked',
  '删除会话': 'Delete conversation',
  '当前对话 Agent Graph': 'Agent Graph for this conversation',
  '查看运行事件': 'View runtime events',
  '切换自动旋转': 'Toggle automatic rotation',
  '全屏查看': 'View full screen',
  '协作与业务资产': 'Collaboration and business assets',
  '新建项目': 'New project',
  '记忆': 'Memory',
  '能力': 'Capabilities',
  '方案': 'Solutions',
  '效能': 'Performance',
  '把目标、任务、Nexus 和交付放在同一处。': 'Keep goals, tasks, Nexus flows, and deliverables in one place.',
  '项目空间栏目': 'Project sections',
  '复用稳定流程': 'Reuse proven processes',
  '个可用': 'available',
  '快速开始': 'Quick start',
  '个模板': 'templates',
  '行业资讯': 'Industry briefing',
  '按时间与主题收集行业动态，去重并形成可追溯简报。': 'Collect industry updates by time and topic, remove duplicates, and produce a traceable briefing.',
  '创建草稿': 'Create draft',
  '论文调研': 'Paper research',
  '检索论文、复核方法与证据，形成有引用边界的综述。': 'Find papers, review methods and evidence, and produce a review with clear citation boundaries.',
  'GitHub 项目评估': 'GitHub project assessment',
  '核查仓库架构、维护活跃度、风险与接入成本。': 'Assess repository architecture, maintenance activity, risks, and integration cost.',
  '竞品研究': 'Competitive research',
  '比较能力、体验、价格和可验证差异。': 'Compare capabilities, experience, pricing, and verifiable differences.',
  '需求分析': 'Requirements analysis',
  '把目标和想法整理成可验收、可实施的产品需求。': 'Turn goals and ideas into testable, implementable product requirements.',
  '数据报告': 'Data report',
  '校验口径、分析指标和异常，形成可交付报告。': 'Validate definitions, analyze metrics and anomalies, and produce a deliverable report.',
  '营销素材': 'Marketing content',
  '基于受众与已验证卖点生成多渠道素材。': 'Create multi-channel content for the audience using verified product claims.',
  '工作总结': 'Work summary',
  '从真实记录提炼完成项、影响、风险和下一步。': 'Summarize completed work, impact, risks, and next steps from actual records.',
  '文档审查': 'Document review',
  '检查结构、一致性、证据、遗漏和可读性。': 'Review structure, consistency, evidence, omissions, and readability.',
  '插件生成': 'Plugin builder',
  '定义交互、Agent、工具权限与验收，生成可审核插件。': 'Define interactions, Agents, tool permissions, and acceptance criteria for a reviewable plugin.',
  '代码审查': 'Code review',
  '并行收集变更上下文、分析风险，再经过质量门禁输出可执行审查意见。': 'Collect change context in parallel, analyze risk, and produce actionable findings through a quality gate.',
  '架构评估': 'Architecture assessment',
  '比较架构方案、识别生产风险、明确成本与恢复权衡，并保留验证标准。': 'Compare architectures, identify production risks, clarify cost and recovery tradeoffs, and retain verification criteria.',
  '故障分析': 'Incident analysis',
  '重建故障时间线，区分事实与假设，生成缓解、恢复和防复发动作。': 'Reconstruct the incident timeline, separate facts from assumptions, and define mitigation, recovery, and prevention actions.',
  '研究报告': 'Research report',
  '收集边界明确的证据，分析观点和不确定性，形成带引用范围的研究结论。': 'Collect bounded evidence, analyze viewpoints and uncertainty, and produce research conclusions with scoped citations.',
  '个人与团队': 'Personal and team',
  '可从标准模板创建，或导入 JSON 模板': 'Create from a standard template or import a JSON template',
  '刷新模板': 'Refresh templates',
  '新建': 'New',
  '校验': 'Validate',
  '设置': 'Settings',
  '保存': 'Save',
  '尚未保存 Agent Nexus': 'Agent Nexus has not been saved',
  '平台 Agent': 'Platform Agents',
  '收集资料、事实、约束、假设和可验证证据。': 'Collect material, facts, constraints, assumptions, and verifiable evidence.',
  '分析方案、权衡、风险、决策标准和验证方式。': 'Analyze options, tradeoffs, risks, decision criteria, and validation methods.',
  '构建可执行结果、实现方案和审查修正。': 'Build executable results, implementations, and review corrections.',
  '检查完整性、一致性、证据质量和可执行性。': 'Check completeness, consistency, evidence quality, and executability.',
  '汇总员': 'Synthesizer',
  '汇总通过验证的结果，生成最终用户答案和 Artifact。': 'Combine verified results into the final response and Artifact.',
  '联网搜索 Agent': 'Web Search Agent',
  '使用 DeepSeek 原生 web_search 检索并核验时效性信息。': 'Use DeepSeek native web_search to retrieve and verify time-sensitive information.',
  '论文搜索 Agent': 'Paper Search Agent',
  '检索论文、DOI 与权威学术来源。': 'Find papers, DOIs, and authoritative academic sources.',
  'GitHub 研究 Agent': 'GitHub Research Agent',
  '检索仓库、Release、文档、Issue 与许可证。': 'Research repositories, Releases, documentation, Issues, and licenses.',
  '绘图 Agent': 'Image Agent',
  '调用平台绘图模型生成图片，并把图片结果交给下游 Agent 或输出端。': 'Use the configured image model and pass results to downstream Agents or the output.',
  '视频制作 Agent': 'Video Agent',
  '尚未配置服务端视频模型。': 'The server-side video model is not configured.',
  '仅此 Nexus': 'This Nexus only',
  '普通连线': 'Standard connection',
  'Loop 回边': 'Loop return edge',
  '内置': 'Built in',
  '输入内容，按当前 Agent 流水线执行': 'Enter content to run through the current Agent flow',
  'Agent 状态、分支和 Loop 轮次会实时显示在画布中。': 'Agent status, branches, and Loop iterations appear on the canvas in real time.',
  '存在未保存更改': 'Unsaved changes',
  '创建 Nexus 私有 Agent': 'Create a private Nexus Agent',
  '连线类型': 'Connection type',
  '缩小': 'Zoom out',
  '放大': 'Zoom in',
  '重置画布': 'Reset canvas',
  'Agent Nexus 连线': 'Agent Nexus connection',
  '向 Agent Nexus 输入内容': 'Enter content for Agent Nexus',
  '周一': 'Mon',
  '周二': 'Tue',
  '周三': 'Wed',
  '周四': 'Thu',
  '周五': 'Fri',
  '周六': 'Sat',
  '周日': 'Sun',
  '例如：每天早上 9 点搜索 Agent 行业动态，整理成 5 条摘要并保留来源': 'For example: every day at 9 AM, research Agent industry news and prepare five sourced highlights',
  '例如：运行时健康巡检': 'For example: runtime health check',
  '到点后需要完成什么': 'What should be completed at run time?',
  'Agent 工作室': 'Agent Studio',
  '小时的真实任务、事件和租约。': 'hours of actual tasks, events, and leases.',
  '24 小时': '24 hours',
  '3 天': '3 days',
  '7 天': '7 days',
  '同步中…': 'Syncing...',
  '正在读取运行数据': 'Loading runtime data',
  '等待数据': 'Waiting for data',
  '当前没有排队任务': 'No tasks are queued',
  'Worker 租约': 'Worker leases',
  '租约状态正常': 'Lease status healthy',
  '交付成功率': 'Delivery success rate',
  '暂无终态任务': 'No terminal tasks',
  'P95 完成时长': 'P95 completion time',
  '服务未达到运行条件': 'A service is not ready',
  '文本模型服务': 'Text model service',
  '立即处理': 'Act now',
  '个活动任务': 'active tasks',
  '规划中': 'Planning',
  '执行中': 'Executing',
  '审查中': 'Reviewing',
  '等待确认': 'Awaiting confirmation',
  '已暂停': 'Paused',
  '当前没有持有租约的 Worker。': 'No Worker currently holds a lease.',
  '个模型': 'models',
  '这段时间还没有模型调用。': 'No model calls in this period.',
  '个工具': 'tools',
  '这段时间没有工具调用。': 'No tool calls in this period.',
  'Agent 协作': 'Agent collaboration',
  '个 Agent': 'Agents',
  '这段时间没有 Agent 执行记录。': 'No Agent executions in this period.',
  '次审查': 'reviews',
  '审查通过': 'Review passed',
  '人工接管': 'Human intervention',
  '审查启动': 'Review started',
  '终态任务': 'Terminal tasks',
  '完成': 'Completed',
  '失败': 'Failed',
  '长对话整理': 'Long-conversation compaction',
  '个有效摘要': 'valid summaries',
  '长对话达到整理阈值后，这里会显示压缩和复用情况。': 'Compaction and reuse appear here after a long conversation reaches the threshold.',
  'Artifact 存储': 'Artifact storage',
  '重试清理': 'Retry cleanup',
  '有效': 'Active',
  '孤儿': 'Orphaned',
  '待清理': 'Pending cleanup',
  '字节': 'bytes',
  '统计时间范围': 'Statistics time range',
  '重试清理队列': 'Retry cleanup queue',
  '可复用工具': 'Reusable tools',
  '个': 'items',
  '刷新插件': 'Refresh plugins',
  '插件视图': 'Plugin view',
  '服务处于受限模式': 'Services are running in limited mode',
  '请先处理下方标红的服务。': 'Resolve the services marked in red below first.',
  '模型服务暂时不可用': 'Model services are temporarily unavailable',
  '已阻断': 'Blocked',
  '租户身份签名；视频模型服务；长期记忆': 'Tenant identity signing; video model service; long-term memory',
  '需要关注': 'Attention required',
  '实时检测': 'Live checks',
  '模型服务': 'Model services',
  '对话可用，部分媒体未开启': 'Chat is available; some media capabilities are disabled',
  '需关注': 'Attention required',
  '任务记录': 'Task records',
  '任务和日程会可靠保存': 'Tasks and schedules are stored reliably',
  '就绪': 'Ready',
  '文件与工具': 'Files and tools',
  '基础文件能力可用': 'Core file capabilities are available',
  '长期记忆': 'Long-term memory',
  '当前任务不受影响': 'The current task is not affected',
  '查看技术详情': 'View technical details',
  '持久化存储': 'Durable storage',
  '已配置 PostgreSQL 租约存储。': 'PostgreSQL lease storage is configured.',
  '上线前需处理': 'Resolve before launch',
  'API 身份认证': 'API authentication',
  '尚未配置网关密钥，只能在可信私有网络中使用。': 'No gateway secret is configured. Use only within a trusted private network.',
  '租户身份签名': 'Tenant identity signing',
  '尚未配置身份签名密钥，租户请求头只能在私有代理后被信任。': 'No identity signing key is configured. Tenant headers are trusted only behind a private proxy.',
  '文本模型服务健康检查通过。': 'The text model service passed its health check.',
  '文本模型服务健康检查失败。': 'The text model service failed its health check.',
  '任务模型配置保护': 'Task model configuration protection',
  '任务模型配置可加密保存并在重启后恢复。': 'Task model settings can be stored encrypted and restored after a restart.',
  '请配置并备份 AXIOM_PROVIDER_SECRET；任务入队需要加密保存模型配置，所有 Worker 必须使用同一密钥。': 'Configure and back up AXIOM_PROVIDER_SECRET. Task model settings must be encrypted before queueing, and all Workers must use the same key.',
  '图像模型服务': 'Image model service',
  '视频模型服务': 'Video model service',
  '填写本地视频服务 URL 和模型名称后，视频制作 Agent 才能使用。': 'Configure the local video service URL and model name to enable the Video Agent.',
  '记忆适配器未启用，不同运行之间不会保留工作流记忆。': 'The memory adapter is disabled; workflow memory will not persist between runs.',
  'Harness 边车服务': 'Harness sidecar',
  '当前使用内置调度器，边车服务为可选项。': 'The built-in scheduler is active; a sidecar is optional.',
  '沙箱工具执行器': 'Sandbox tool runner',
  '沙箱镜像 ubuntu:22.04 可用。': 'The ubuntu:22.04 sandbox image is available.',
  'Artifact 对象存储': 'Artifact object storage',
  '本地 Artifact 目录可读写。': 'The local Artifact directory is readable and writable.',
  '指标与链路追踪': 'Metrics and tracing',
  '已启用 Prometheus 指标。': 'Prometheus metrics are enabled.',
  'Webhook 与调度持久性': 'Webhook and scheduler durability',
  'PostgreSQL 调度器已持久化并使用租约安全的到期任务领取机制；Webhook 触发器为可选项且当前未启用。': 'The PostgreSQL scheduler is durable and claims due work with leases; Webhook triggers are optional and currently disabled.',
  '可用工具': 'Available tools',
  '创建自定义 Agent 定义草稿并交由人工审核；不会自动发布或启用该角色。': 'Create a custom Agent definition draft for human review; the role is not published or enabled automatically.',
  '低风险': 'Low risk',
  '使用 ripgrep 搜索已挂载的任务工作区；只读且与网络隔离。': 'Search the mounted task workspace with ripgrep in read-only, network-isolated mode.',
  '从已挂载的任务工作区读取 UTF-8 文本文件。': 'Read a UTF-8 text file from the mounted task workspace.',
  '从已挂载的工作区读取大小受限的文本文档，支持 Markdown、JSON、YAML、XML 和纯文本。': 'Read a size-limited document from the mounted workspace, including Markdown, JSON, YAML, XML, and plain text.',
  '读取大小受限的 CSV 或 JSON 表格并返回规范化数据行，不修改工作区。': 'Read a size-limited CSV or JSON table and return normalized rows without modifying the workspace.',
  '仅使用 GET/HEAD 获取 JSON 或文本 API 响应；目标主机必须位于 AXIOM_HTTP_ALLOWLIST。': 'Fetch JSON or text API responses with GET/HEAD only; the host must be in AXIOM_HTTP_ALLOWLIST.',
  '中风险': 'Medium risk',
  '通过只读浏览器适配器打开白名单中的公开 URL，并返回页面文本。': 'Open an allowlisted public URL through the read-only browser adapter and return page text.',
  '通过 AXIOM_READONLY_DATABASE_URL 或 DATABASE_URL 执行一条受限的只读 SQL 查询。': 'Run one restricted read-only SQL query through AXIOM_READONLY_DATABASE_URL or DATABASE_URL.',
  '检查仓库状态，不修改文件。': 'Inspect repository status without modifying files.',
  '读取当前 Git 差异，不修改文件。': 'Read the current Git diff without modifying files.',
  '读取当前 Git 分支和本地分支列表。': 'Read the current Git branch and local branch list.',
  '读取近期本地 Git 提交，不修改仓库。': 'Read recent local Git commits without modifying the repository.',
  '在已挂载的工作区运行白名单中的 npm 脚本。': 'Run an allowlisted npm script in the mounted workspace.',
  '获得明确人工批准后写入 UTF-8 文件。': 'Write a UTF-8 file after explicit human approval.',
  '直接生成本次任务的独立 HTML、SVG、Markdown 或文本交付文件，无需人工确认。仅保存为任务附件，不执行内容、不访问或修改项目文件。用户要求画 SVG、制作网页动画或生成文档时优先使用；修改已有项目文件仍须使用 workspace.write/patch 并申请批准。': 'Create a standalone HTML, SVG, Markdown, or text deliverable for this task without a separate approval. Save it as a task attachment only; do not execute its content or access or modify project files. Prefer this for SVG drawings, webpage animations, and documents. Changing existing project files still requires workspace.write/patch and approval.',
  '获得明确人工批准后写入或覆盖已有项目工作区中的 UTF-8 文件。用户仅需独立 HTML、SVG 或文档交付时使用 artifact.create，无需修改项目文件。': 'Write or overwrite a UTF-8 file in an existing project workspace after explicit human approval. Use artifact.create for standalone HTML, SVG, or document deliverables that do not require changing project files.',
  '高风险': 'High risk',
  '· 需确认': '· confirmation required',
  '获得明确人工批准后，精确替换 UTF-8 文件中的文本片段。': 'Precisely replace text in a UTF-8 file after explicit human approval.',
  '工具注册表': 'Tool Registry',
  '默认使用 deepseek-chat': 'Default: deepseek-chat',
  '默认使用 deepseek-v4-flash-vision-exp': 'Default: deepseek-v4-flash-vision-exp',
  '默认使用 gpt-image-2-03': 'Default: gpt-image-2-03',
  'API Key（可选）': 'API Key (optional)',
  'API Key 默认仅用于当前请求；点击“安全保存凭据”后会加密保存在服务端，浏览器只保留引用 ID。': 'By default, the API Key is used only for the current request. “Store credential securely” encrypts it on the server; the browser keeps only a reference ID.',
  '系统会自动选择任务所需的模型': 'The system automatically selects the model required by the task',
  '服务来源': 'Service source',
  'API Key 仅加密保存在服务端，不会写入浏览器存储': 'The API Key is encrypted on the server and is never written to browser storage',
  'http://127.0.0.1:端口': 'http://127.0.0.1:PORT',
  '填写本地视频模型名称': 'Enter the local video model name',
  '当前没有待办通知': 'No pending notifications',
  '站内通知': 'Notifications',
  '外发渠道': 'Delivery channels',
  '全部已读': 'Mark all as read',
};

const dynamicEnglish: Array<[RegExp, (...matches: string[]) => string]> = [
  [/^已配置本地视频模型 (.+)。$/, (model) => `Local video model ${model} is configured.`],
  [/^已配置 (.+)，尚未探测模型服务连通性。$/, (model) => `${model} is configured; model connectivity has not been checked.`],
  [/^已配置 (.+)。$/, (model) => `${model} is configured.`],
  [/^主题：(.+)$/, (value) => `Theme: ${translateUiText(value, 'en')}`],
  [/^选择主题，当前为(.+)$/, (value) => `Choose theme. Current: ${translateUiText(value, 'en')}`],
  [/^删除会话\s+(.+)$/, (value) => `Delete conversation ${value}`],
  [/^删除任务\s+(.+)$/, (value) => `Delete task ${value}`],
  [/^删除插件\s+(.+)$/, (value) => `Delete plugin ${value}`],
  [/^修改插件\s+(.+)$/, (value) => `Edit plugin ${value}`],
  [/^发布插件\s+(.+)$/, (value) => `Publish plugin ${value}`],
  [/^打开插件\s+(.+)$/, (value) => `Open plugin ${value}`],
  [/^卸载(?:市场)?插件\s+(.+)$/, (value) => `Uninstall plugin ${value}`],
  [/^提交市场\s+(.+)$/, (value) => `Submit to market ${value}`],
  [/^撤回市场\s+(.+)$/, (value) => `Withdraw from market ${value}`],
  [/^删除(.+)$/, (value) => `Delete ${value}`],
  [/^(意图|计划|执行|审查|交付)：(已完成|进行中|未完成|未启用)$/, (stage, status) => `${translateUiText(stage, 'en')}: ${translateUiText(status, 'en')}`],
  [/^今天\s+(.+)$/, (value) => `Today ${value}`],
  [/^昨天\s+(.+)$/, (value) => `Yesterday ${value}`],
  [/^平均时长\s+(.+)$/, (value) => `Average duration ${translateUiText(value, 'en')}`],
  [/^([\d.]+)\s*秒$/, (value) => `${value} sec`],
  [/^([\d.]+)\s*分钟$/, (value) => `${value} min`],
  [/^(\d+)\s*个 Agent$/, (value) => `${value} Agents`],
  [/^(\d+)\s*个推理节点(?:\s*·\s*(.+))?$/, (value, suffix) => `${value} reasoning nodes${suffix ? ` · ${suffix}` : ''}`],
  [/^(\d+)\s*个任务$/, (value) => `${value} tasks`],
  [/^(\d+)\s*星$/, (value) => `${value} ${value === '1' ? 'star' : 'stars'}`],
  [/^(\d+)\s*项未完成$/, (value) => `${value} incomplete ${value === '1' ? 'step' : 'steps'}`],
  [/^工具：(.+)$/, (value) => `Tool: ${value}`],
  [/^(\d+)\s*个终态任务$/, (value) => `${value} terminal tasks`],
  [/^(\d+)\s*个会话$/, (value) => `${value} conversations`],
  [/^(\d+)\s*个工具$/, (value) => `${value} tools`],
  [/^(\d+)\s*个模型$/, (value) => `${value} models`],
  [/^(\d+)\s*条事件$/, (value) => `${value} events`],
  [/^(\d+)\s*条未读$/, (value) => `${value} unread`],
  [/^(\d+)\s*条$/, (value) => `${value} items`],
  [/^版本\s+(.+)$/, (value) => `Version ${value}`],
  [/^当前版本\s+(.+)$/, (value) => `Current version ${value}`],
  [/^下次\s+(.+)$/, (value) => `Next: ${value}`],
  [/^较过去 24 小时\s+(.+)$/, (value) => `${value} vs previous 24 hours`],
  [/^(.+)正在执行“(.+)”$/, (agent, step) => `${agent} is executing “${step}”`],
  [/^(.+)正在执行当前步骤$/, (agent) => `${agent} is executing the current step`],
  [/^(.+)正在执行$/, (agent) => `${agent} is executing`],
  [/^(.+)的阶段调用未完成$/, (agent) => `${agent}'s stage call did not complete`],
  [/^Loop 第 (\d+) \/ (\d+) 轮$/, (iteration, total) => `Loop iteration ${iteration} / ${total}`],
  [/^“(.+)”最近两次未满足结果接续条件；此前运行曾执行完成，并有可追溯来源或人工接受记录。$/, (title) => `The two latest runs of "${title}" did not meet the criteria for reuse; earlier runs completed with traceable sources or recorded human acceptance.`],
  [/^(\d+)月(\d+)日周([一二三四五六日])$/, (month, day, weekday) => `${month}/${day} ${translateUiText(`周${weekday}`, 'en')}`],
  [/^刚刚更新\s*·\s*(.+)$/, (time) => `Updated just now · ${time}`],
  [/^默认使用\s+(.+)$/, (model) => `Default: ${model}`],
  [/^(\d+)\s*条提醒$/, (value) => `${value} alerts`],
  [/^(\d+)\s*项需要处理(。)?$/, (value, punctuation) => `${value} ${value === '1' ? 'item requires' : 'items require'} attention${punctuation ? '.' : ''}`],
  [/^从\s+(.+)\s+开始连线$/, (value) => `Start a connection from ${value}`],
  [/^连接到\s+(.+)$/, (value) => `Connect to ${value}`],
  [/^(\d+)\s*个 Agent\s*·\s*(\d+)\s*条连接$/, (agents, edges) => `${agents} Agent · ${edges} connections`],
];

const preservedSelectors = [
  'pre',
  'code',
  'script',
  'style',
  '[data-i18n-ignore="true"]',
  '.dash-chat-markdown',
  '.dash-chat-artifact-markdown',
  '.task-evidence-claim p',
  '.dash-plugin-preview-frame',
];

const preservedSelector = preservedSelectors.join(',');
const localizedAttributes = ['aria-label', 'title', 'placeholder', 'alt'] as const;
const textRecords = new WeakMap<Text, { source: string; rendered: string }>();
const attributeRecords = new WeakMap<Element, Map<string, { source: string; rendered: string }>>();

export const normalizeUiLanguage = (value: string | null | undefined): UiLanguage | null => {
  const normalized = value?.trim().toLowerCase();
  if (normalized === 'en' || normalized === 'en-us' || normalized === 'en-gb') return 'en';
  if (normalized === 'zh' || normalized === 'zh-cn' || normalized === 'zh-hans') return 'zh-CN';
  return null;
};

export const translateUiText = (source: string, language: UiLanguage): string => {
  if (language === 'zh-CN' || !/[\u3400-\u9fff]/u.test(source)) return source;
  const leading = source.match(/^\s*/u)?.[0] ?? '';
  const trailing = source.match(/\s*$/u)?.[0] ?? '';
  const value = source.slice(leading.length, source.length - trailing.length || undefined);
  const exact = englishByChinese[value];
  if (exact) return `${leading}${exact}${trailing}`;
  for (const [pattern, format] of dynamicEnglish) {
    const match = value.match(pattern);
    if (match) return `${leading}${format(...match.slice(1))}${trailing}`;
  }
  return source;
};

export const resolveInitialUiLanguage = (input: { query?: string; stored?: string | null } = {}): UiLanguage => {
  const queryValue = input.query ? new URLSearchParams(input.query).get('lang') : null;
  return normalizeUiLanguage(queryValue) ?? normalizeUiLanguage(input.stored) ?? DEFAULT_UI_LANGUAGE;
};

const shouldPreserve = (element: Element | null) => Boolean(element?.closest(preservedSelector));

const localizeTextNode = (node: Text, language: UiLanguage) => {
  if (shouldPreserve(node.parentElement)) return;
  const current = node.nodeValue ?? '';
  const previous = textRecords.get(node);
  const source = previous && (current === previous.rendered || current === previous.source) ? previous.source : current;
  const rendered = translateUiText(source, language);
  textRecords.set(node, { source, rendered });
  if (current !== rendered) node.nodeValue = rendered;
};

const localizeElementAttributes = (element: Element, language: UiLanguage) => {
  if (shouldPreserve(element)) return;
  const records = attributeRecords.get(element) ?? new Map<string, { source: string; rendered: string }>();
  for (const name of localizedAttributes) {
    const current = element.getAttribute(name);
    if (current === null) continue;
    const previous = records.get(name);
    const source = previous && (current === previous.rendered || current === previous.source) ? previous.source : current;
    const rendered = translateUiText(source, language);
    records.set(name, { source, rendered });
    if (current !== rendered) element.setAttribute(name, rendered);
  }
  attributeRecords.set(element, records);
};

const localizeTree = (root: Node, language: UiLanguage) => {
  if (root.nodeType === Node.TEXT_NODE) {
    localizeTextNode(root as Text, language);
    return;
  }
  if (!(root instanceof Element) && !(root instanceof Document)) return;
  if (root instanceof Element) localizeElementAttributes(root, language);
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT);
  let current = walker.nextNode();
  while (current) {
    if (current.nodeType === Node.TEXT_NODE) localizeTextNode(current as Text, language);
    else localizeElementAttributes(current as Element, language);
    current = walker.nextNode();
  }
};

const loadBrowserLanguage = (): UiLanguage => {
  try {
    return resolveInitialUiLanguage({ query: window.location.search, stored: window.localStorage.getItem(UI_LANGUAGE_STORAGE_KEY) });
  } catch {
    return DEFAULT_UI_LANGUAGE;
  }
};

export function UiLanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<UiLanguage>(loadBrowserLanguage);

  const setLanguage = useCallback((next: UiLanguage) => {
    setLanguageState(next);
    try {
      window.localStorage.setItem(UI_LANGUAGE_STORAGE_KEY, next);
      const url = new URL(window.location.href);
      url.searchParams.set('lang', next);
      window.history.replaceState(window.history.state, '', url);
    } catch {
      // Storage and history are optional; the in-memory selection still works.
    }
  }, []);

  useLayoutEffect(() => {
    document.documentElement.lang = language;
    const root = document.getElementById('root');
    if (!root) return;
    let applying = false;
    const apply = (node: Node) => {
      if (applying) return;
      applying = true;
      localizeTree(node, language);
      applying = false;
    };
    apply(root);
    const observer = new MutationObserver((mutations) => {
      observer.disconnect();
      for (const mutation of mutations) {
        if (mutation.type === 'characterData') apply(mutation.target);
        mutation.addedNodes.forEach(apply);
        if (mutation.type === 'attributes') apply(mutation.target);
      }
      observer.observe(root, { subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: [...localizedAttributes] });
    });
    observer.observe(root, { subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: [...localizedAttributes] });
    return () => observer.disconnect();
  }, [language]);

  const value = useMemo<UiLanguageContextValue>(() => ({
    language,
    setLanguage,
    t: (source) => translateUiText(source, language),
  }), [language, setLanguage]);

  return <UiLanguageContext.Provider value={value}>{children}</UiLanguageContext.Provider>;
}

export const useUiLanguage = () => {
  const context = useContext(UiLanguageContext);
  if (!context) throw new Error('useUiLanguage must be used within UiLanguageProvider.');
  return context;
};
